//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTapioef001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANTEN
    {
        public string ART_CODE { get; set; }
        public string PLANTENNAAM { get; set; }
        public string SOORT { get; set; }
        public string KLEUR { get; set; }
        public Nullable<double> HOOGTE { get; set; }
        public Nullable<double> BLOEIBEGIN { get; set; }
        public Nullable<double> BLOEIEINDE { get; set; }
        public double PRIJS { get; set; }
    }
}
